import { createContext, useContext, useState, useEffect } from "react";

export type Language = "ms" | "en";

const translations = {
  ms: {
    appName: "PadiCare",
    tagline: "Rakan Pertanian Padi Anda",
    login: "Log Masuk",
    register: "Daftar",
    logout: "Log Keluar",
    home: "Utama",
    tasks: "Tugas",
    myFarm: "Ladang Saya",
    diseaseDetection: "Pengesanan Penyakit",
    resources: "Perancangan Sumber",
    weather: "Cuaca",
    notifications: "Pemberitahuan",
    tutorial: "Panduan",
    name: "Nama",
    email: "E-mel",
    password: "Kata Laluan",
    phone: "Nombor Telefon",
    language: "Bahasa",
    malay: "Bahasa Melayu",
    english: "English",
    submit: "Hantar",
    cancel: "Batal",
    save: "Simpan",
    delete: "Padam",
    edit: "Edit",
    create: "Cipta",
    loading: "Memuatkan...",
    error: "Ralat",
    success: "Berjaya",
    noData: "Tiada data",
    farm: "Ladang",
    farms: "Ladang-ladang",
    addFarm: "Tambah Ladang",
    farmName: "Nama Ladang",
    location: "Lokasi",
    paddyType: "Jenis Padi",
    farmSize: "Saiz Ladang (hektar)",
    paddyAge: "Umur Padi (minggu)",
    growthPhase: "Fasa Pertumbuhan",
    notes: "Nota",
    previousIssues: "Masalah Lepas",
    nursery: "Tapak Semaian",
    vegetative: "Pertumbuhan",
    reproductive: "Pembiakan",
    ripening: "Pemasakan",
    harvested: "Dituai",
    flood: "Banjir",
    rats: "Tikus",
    blast: "Barah Padi",
    blight: "Layu Padi",
    tungro: "Tungro",
    sheath_rot: "Reput Pelepah",
    other: "Lain-lain",
    task: "Tugas",
    taskTitle: "Tajuk Tugas",
    description: "Penerangan",
    status: "Status",
    priority: "Keutamaan",
    dueDate: "Tarikh Akhir",
    pending: "Belum Mula",
    in_progress: "Sedang Berjalan",
    done: "Selesai",
    low: "Rendah",
    medium: "Sederhana",
    high: "Tinggi",
    addTask: "Tambah Tugas",
    filterByFarm: "Tapis mengikut Ladang",
    filterByStatus: "Tapis mengikut Status",
    allFarms: "Semua Ladang",
    allStatuses: "Semua Status",
    detectDisease: "Kesan Penyakit",
    uploadImage: "Muat Naik Gambar",
    cameraMode: "Kamera",
    history: "Sejarah",
    analyze: "Analisa",
    analyzing: "Menganalisis gambar dengan AI...",
    diseaseResult: "Keputusan Pengesanan",
    severity: "Tahap Keterukan",
    ringan: "Ringan",
    sedang: "Sedang",
    parah: "Parah",
    confidence: "Keyakinan",
    treatment: "Rawatan",
    riskFactors: "Faktor Risiko",
    preventionTips: "Tip Pencegahan",
    listenVoice: "Dengar Suara",
    stopVoice: "Henti Suara",
    voiceInput: "Input Suara",
    resourcePlan: "Rancangan Sumber",
    getPlan: "Dapatkan Rancangan",
    fertilizer: "Baja",
    pesticide: "Racun Perosak",
    waterManagement: "Pengurusan Air",
    laborEstimate: "Anggaran Tenaga Kerja",
    estimatedCost: "Kos Anggaran",
    nextActivities: "Aktiviti Seterusnya",
    weatherWarnings: "Amaran Cuaca",
    temperature: "Suhu",
    humidity: "Kelembapan",
    rainfall: "Hujan",
    windSpeed: "Kelajuan Angin",
    forecast: "Ramalan",
    markRead: "Tandakan Dibaca",
    markAllRead: "Tandakan Semua Dibaca",
    noNotifications: "Tiada pemberitahuan",
    dashboard: "Papan Pemuka",
    totalFarms: "Jumlah Ladang",
    totalHectares: "Jumlah Hektar",
    pendingTasks: "Tugas Tertunggak",
    recentDetections: "Pengesanan Terkini",
    quickActions: "Tindakan Pantas",
    scanNow: "Imbas Sekarang",
    viewFarms: "Lihat Ladang",
    checkWeather: "Semak Cuaca",
    planResources: "Rancang Sumber",
    offlineMode: "Mod Luar Talian",
    tutorialWelcome: "Selamat Datang ke PadiCare",
    step: "Langkah",
    next: "Seterusnya",
    previous: "Sebelumnya",
    finish: "Selesai",
    demoHint: "Akaun demo: demo@padicare.my / demo123",
    loginTitle: "Log Masuk PadiCare",
    registerTitle: "Daftar Akaun Baru",
    noAccount: "Belum ada akaun?",
    hasAccount: "Sudah ada akaun?",
    hectares: "hektar",
    personDays: "hari-orang",
    quantityPerHa: "Kuantiti/hektar",
    applicationTiming: "Masa Penggunaan",
    perHectare: "per hektar",
    myr: "RM",
    uploadPrompt: "Klik atau seret gambar daun padi ke sini",
    supportedFormats: "Format: JPG, PNG, WEBP",
    detectBtn: "Kesan Penyakit",
    noFarmSelected: "Pilih Ladang",
    selectFarm: "Pilih ladang...",
    selectPhase: "Pilih fasa...",
    selectPaddyType: "Pilih jenis padi...",
    selectPriority: "Pilih keutamaan...",
    selectStatus: "Pilih status...",
    deleteConfirm: "Adakah anda pasti mahu memadam?",
    yes: "Ya",
    no: "Tidak",
    close: "Tutup",
    back: "Kembali",
    viewDetails: "Lihat Butiran",
    addIssue: "Tambah Masalah",
    issueType: "Jenis Masalah",
    occurredAt: "Tarikh Berlaku",
    modelUsed: "Model AI",
    detectedAt: "Dikesan Pada",
    healthy: "Sihat",
    today: "Hari Ini",
    recordVoice: "Rakam Suara",
    stopRecording: "Henti Rakaman",
    listenResult: "Dengar Keputusan",
    photoCaptured: "Gambar diambil",
    capturePhoto: "Ambil Gambar",
    cameraPermission: "Sila benarkan akses kamera",
    imageTooLarge: "Saiz gambar terlalu besar (maks 5MB)",
    uploadSuccess: "Gambar berjaya dimuat naik",
    phase: "Fasa",
    weeks: "Minggu",
    size: "Saiz",
    type: "Jenis",
    noFarms: "Tiada ladang. Tambah ladang pertama anda!",
    noTasks: "Tiada tugas.",
    noHistory: "Tiada sejarah pengesanan.",
    addNewFarm: "Tambah Ladang Baru",
    editFarm: "Edit Ladang",
  },
  en: {
    appName: "PadiCare",
    tagline: "Your Paddy Farming Companion",
    login: "Login",
    register: "Register",
    logout: "Logout",
    home: "Home",
    tasks: "Tasks",
    myFarm: "My Farm",
    diseaseDetection: "Disease Detection",
    resources: "Resource Planning",
    weather: "Weather",
    notifications: "Notifications",
    tutorial: "Tutorial",
    name: "Name",
    email: "Email",
    password: "Password",
    phone: "Phone Number",
    language: "Language",
    malay: "Bahasa Melayu",
    english: "English",
    submit: "Submit",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    create: "Create",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    noData: "No data",
    farm: "Farm",
    farms: "Farms",
    addFarm: "Add Farm",
    farmName: "Farm Name",
    location: "Location",
    paddyType: "Paddy Type",
    farmSize: "Farm Size (hectares)",
    paddyAge: "Paddy Age (weeks)",
    growthPhase: "Growth Phase",
    notes: "Notes",
    previousIssues: "Previous Issues",
    nursery: "Nursery",
    vegetative: "Vegetative",
    reproductive: "Reproductive",
    ripening: "Ripening",
    harvested: "Harvested",
    flood: "Flood",
    rats: "Rats",
    blast: "Blast",
    blight: "Blight",
    tungro: "Tungro",
    sheath_rot: "Sheath Rot",
    other: "Other",
    task: "Task",
    taskTitle: "Task Title",
    description: "Description",
    status: "Status",
    priority: "Priority",
    dueDate: "Due Date",
    pending: "Pending",
    in_progress: "In Progress",
    done: "Done",
    low: "Low",
    medium: "Medium",
    high: "High",
    addTask: "Add Task",
    filterByFarm: "Filter by Farm",
    filterByStatus: "Filter by Status",
    allFarms: "All Farms",
    allStatuses: "All Statuses",
    detectDisease: "Detect Disease",
    uploadImage: "Upload Image",
    cameraMode: "Camera",
    history: "History",
    analyze: "Analyze",
    analyzing: "Analyzing image with AI...",
    diseaseResult: "Detection Result",
    severity: "Severity",
    ringan: "Mild",
    sedang: "Moderate",
    parah: "Severe",
    confidence: "Confidence",
    treatment: "Treatment",
    riskFactors: "Risk Factors",
    preventionTips: "Prevention Tips",
    listenVoice: "Listen",
    stopVoice: "Stop",
    voiceInput: "Voice Input",
    resourcePlan: "Resource Plan",
    getPlan: "Get Plan",
    fertilizer: "Fertilizer",
    pesticide: "Pesticide",
    waterManagement: "Water Management",
    laborEstimate: "Labor Estimate",
    estimatedCost: "Estimated Cost",
    nextActivities: "Next Activities",
    weatherWarnings: "Weather Warnings",
    temperature: "Temperature",
    humidity: "Humidity",
    rainfall: "Rainfall",
    windSpeed: "Wind Speed",
    forecast: "Forecast",
    markRead: "Mark as Read",
    markAllRead: "Mark All Read",
    noNotifications: "No notifications",
    dashboard: "Dashboard",
    totalFarms: "Total Farms",
    totalHectares: "Total Hectares",
    pendingTasks: "Pending Tasks",
    recentDetections: "Recent Detections",
    quickActions: "Quick Actions",
    scanNow: "Scan Now",
    viewFarms: "View Farms",
    checkWeather: "Check Weather",
    planResources: "Plan Resources",
    offlineMode: "Offline Mode",
    tutorialWelcome: "Welcome to PadiCare",
    step: "Step",
    next: "Next",
    previous: "Previous",
    finish: "Finish",
    demoHint: "Demo account: demo@padicare.my / demo123",
    loginTitle: "Login to PadiCare",
    registerTitle: "Create New Account",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    hectares: "hectares",
    personDays: "person-days",
    quantityPerHa: "Quantity/hectare",
    applicationTiming: "Application Timing",
    perHectare: "per hectare",
    myr: "RM",
    uploadPrompt: "Click or drag a paddy leaf image here",
    supportedFormats: "Formats: JPG, PNG, WEBP",
    detectBtn: "Detect Disease",
    noFarmSelected: "Select Farm",
    selectFarm: "Select farm...",
    selectPhase: "Select phase...",
    selectPaddyType: "Select paddy type...",
    selectPriority: "Select priority...",
    selectStatus: "Select status...",
    deleteConfirm: "Are you sure you want to delete?",
    yes: "Yes",
    no: "No",
    close: "Close",
    back: "Back",
    viewDetails: "View Details",
    addIssue: "Add Issue",
    issueType: "Issue Type",
    occurredAt: "Date Occurred",
    modelUsed: "AI Model",
    detectedAt: "Detected At",
    healthy: "Healthy",
    today: "Today",
    recordVoice: "Record Voice",
    stopRecording: "Stop Recording",
    listenResult: "Listen to Result",
    photoCaptured: "Photo captured",
    capturePhoto: "Capture Photo",
    cameraPermission: "Please allow camera access",
    imageTooLarge: "Image too large (max 5MB)",
    uploadSuccess: "Image uploaded successfully",
    phase: "Phase",
    weeks: "Weeks",
    size: "Size",
    type: "Type",
    noFarms: "No farms. Add your first farm!",
    noTasks: "No tasks.",
    noHistory: "No detection history.",
    addNewFarm: "Add New Farm",
    editFarm: "Edit Farm",
  }
};

export type TranslationKey = keyof typeof translations.ms;

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "ms",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const stored = localStorage.getItem("padicare-lang");
    return (stored === "ms" || stored === "en") ? stored : "ms";
  });

  const setLang = (l: Language) => {
    localStorage.setItem("padicare-lang", l);
    setLangState(l);
  };

  const t = (key: TranslationKey): string => {
    return (translations[lang] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
